---
- name - Install Windows Updates
  hosts: all
  gather_facts: false
  tasks:
  - name: Install all updates with automatic reboots
    win_updates:
		category_names:
		- SecurityUpdates
		- CriticalUpdates
		- UpdateRollups		
		reboot: yes
